version: '3'

services:
  postgres:
    image: postgres
    environment:
        POSTGRES_PASSWORD: "dev123"
    restart: always
    ports:
        - "15432:5432"
    volumes:
        - /PostgreSQL:/var/lib/postgresql/data 